service: medium-api
frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  memorySize: 512
  environment:

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'

  # Medias:
  #   handler: index.MediaHandler
  #   events:
  #     - httpApi:
  #         path: /new-feature
  #         method: GET
  # Blogs:
  #   handler: index.latestBlog
  #   events:
  #     - httpApi:
  #         path: /latest-blogs
  #         method: POST